# The font
[font]

# Default structure
# [font.<font_name>] # the name of the font (unique identifier)
# name = "<name of the font>" # set the name of the font  (a human readable name)
# path = "<path to the font file>" # set the path to the file (supported format, ttf, otf [and other SFML Font supported formats])
# default_size = <size> # (0 -> 100) set the default size of the font to display, in pixels
# bold = false # (or true) set the font to bold
# italic = false # (or true) set the font to italic

# The font that will be used for title sections of the program
[font.title]
name = "Color Basic"
path = "assets/font/Color Basic/TTF Fonts/color_basic.ttf"
default_size = 50
bold = false
italic = false

# The font that will be used for the rest of the text to display
[font.body]
name = "Joystix Monospace"
path = "assets/font/Joystix/TTF Fonts/joystix_monospace.ttf"
default_size = 50
bold = false
italic = false

# The music
[music]

# Default structure
# [music.<music_name>] # the name of the music (unique identifier)
# name = "<name of the music>" # set the name of the music  (a human readable name)
# path = "<valid path to the audio file>" # set the path to the file (supported format, ogg, wav [and other SFML Music supported formats])
# loop = true # (or false) # play the music on repeat
# volume = <volume> # (0 -> 100) set the volume of the track to play.

[music.mainMenu]
name = "Main Menu"
path = "assets/audio/2019-12-11_-_Retro_Platforming_-_David_Fesliyan.ogg"
loop = true
volume = 100

[music.bossFight]
name = "Boss Fight"
path = "assets/audio/2021-08-30_-_Boss_Time_-_www.FesliyanStudios.com.ogg"
loop = true
volume = 100

[music.gameLoop]
name = "Game Loop"
path = "assets/audio/FASTER-2020-03-22_-_A_Bit_Of_Hope_-_David_Fesliyan.ogg"
loop = true
volume = 100

[music.shooting]
name = "Shooting"
path = "assets/audio/Laser-A1-www.fesliyanstudios.com.ogg"
loop = false
volume = 100

[music.damage]
name = "Damage"
path = "assets/audio/Undertale_Damage_Sound_Effect.ogg"
loop = false
volume = 100

[music.dead]
name = "Dead"
path = "assets/audio/Bomb-Explosion-Big-www.fesliyanstudios.com.ogg"
loop = false
volume = 100

[music.button]
name = "Button"
path = "assets/audio/Game-Menu-Selection-Z-www.fesliyanstudios.com.ogg"
loop = false
volume = 100

[music.gameOver]
name = "Game Over"
path = "assets/audio/game-over-arcade.ogg"
loop = false
volume = 100

[music.success]
name = "Success"
path = "assets/audio/success-fanfare-trumpets-6185.ogg"
loop = false
volume = 100

# The spritesheets
[spritesheets]

# Default structure
# [spritesheet.<spritesheet_name>] # the name of the spritesheet to load (unique identifier)
# name = "<name of the sprite>" # set the name of the sprite  (a human readable name)
# path = "<valid path to the image file>" # set the path to the file (supported format, gif, png [and other SFML Texture supported formats])
# sprite_width = <width> # (0 -> 1000) set the width of the sprite view field, in pixels
# sprite_height = <height> # (0-> 1000) set the height of the sprite view field, in pixels
# start_left = true # (or false) set the starting position of the sprite view field to start from the left (or not)
# start_top = true # (or false) set the starting position of the sprite view field to start from the top (or not)

# The spritesheets to manage

[spritesheets.sprite1]
name = "r-typesheet1"
path = "assets/img/r-typesheet1.gif"
sprite_width = 20
sprite_height = 20
start_left = true
start_top = true

[spritesheets.sprite2]
name = "r-typesheet2"
path = "assets/img/r-typesheet2.gif"
sprite_width = 20
sprite_height = 20
start_left = true
start_top = true

[spritesheets.sprite3]
name = "r-typesheet3"
path = "assets/img/r-typesheet3.gif"
sprite_width = 20
sprite_height = 20
start_left = true
start_top = true

[spritesheets.sprite5]
name = "r-typesheet5"
path = "assets/img/r-typesheet5.gif"
sprite_width = 20
sprite_height = 20
start_left = true
start_top = true

[spritesheets.sprite7]
name = "r-typesheet7"
path = "assets/img/r-typesheet7.gif"
sprite_width = 20
sprite_height = 20
start_left = true
start_top = true

[spritesheets.sprite8]
name = "r-typesheet8"
path = "assets/img/r-typesheet8.gif"
sprite_width = 20
sprite_height = 20
start_left = true
start_top = true

[spritesheets.sprite9]
name = "r-typesheet9"
path = "assets/img/r-typesheet9.gif"
sprite_width = 20
sprite_height = 20
start_left = true
start_top = true

[spritesheets.sprite10]
name = "r-typesheet10"
path = "assets/img/r-typesheet10.gif"
sprite_width = 20
sprite_height = 20
start_left = true
start_top = true

[spritesheets.sprite11]
name = "r-typesheet11"
path = "assets/img/r-typesheet11.gif"
sprite_width = 20
sprite_height = 20
start_left = true
start_top = true

[spritesheets.sprite12]
name = "r-typesheet12"
path = "assets/img/r-typesheet12.gif"
sprite_width = 20
sprite_height = 20
start_left = true
start_top = true

[spritesheets.sprite13]
name = "r-typesheet13"
path = "assets/img/r-typesheet13.gif"
sprite_width = 20
sprite_height = 20
start_left = true
start_top = true

[spritesheets.sprite14]
name = "r-typesheet14"
path = "assets/img/r-typesheet14.gif"
sprite_width = 20
sprite_height = 20
start_left = true
start_top = true

[spritesheets.sprite16]
name = "r-typesheet16"
path = "assets/img/r-typesheet16.gif"
sprite_width = 20
sprite_height = 20
start_left = true
start_top = true

[spritesheets.sprite17]
name = "r-typesheet17"
path = "assets/img/r-typesheet17.gif"
sprite_width = 20
sprite_height = 20
start_left = true
start_top = true

[spritesheets.sprite18]
name = "r-typesheet18"
path = "assets/img/r-typesheet18.gif"
sprite_width = 20
sprite_height = 20
start_left = true
start_top = true

[spritesheets.sprite19]
name = "r-typesheet19"
path = "assets/img/r-typesheet19.gif"
sprite_width = 20
sprite_height = 20
start_left = true
start_top = true

[spritesheets.sprite20]
name = "r-typesheet20"
path = "assets/img/r-typesheet20.gif"
sprite_width = 20
sprite_height = 20
start_left = true
start_top = true

[spritesheets.sprite21]
name = "r-typesheet21"
path = "assets/img/r-typesheet21.gif"
sprite_width = 20
sprite_height = 20
start_left = true
start_top = true

[spritesheets.sprite22]
name = "r-typesheet22"
path = "assets/img/r-typesheet22.gif"
sprite_width = 20
sprite_height = 20
start_left = true
start_top = true

[spritesheets.sprite23]
name = "r-typesheet23"
path = "assets/img/r-typesheet23.gif"
sprite_width = 20
sprite_height = 20
start_left = true
start_top = true

[spritesheets.sprite24]
name = "r-typesheet24"
path = "assets/img/r-typesheet24.gif"
sprite_width = 20
sprite_height = 20
start_left = true
start_top = true

[spritesheets.sprite25]
name = "r-typesheet25"
path = "assets/img/r-typesheet25.gif"
sprite_width = 20
sprite_height = 20
start_left = true
start_top = true

[spritesheets.sprite26]
name = "r-typesheet26"
path = "assets/img/r-typesheet26.gif"
sprite_width = 20
sprite_height = 20
start_left = true
start_top = true

[spritesheets.sprite27]
name = "r-typesheet27"
path = "assets/img/r-typesheet27.gif"
sprite_width = 20
sprite_height = 20
start_left = true
start_top = true

[spritesheets.sprite28]
name = "r-typesheet28"
path = "assets/img/r-typesheet28.gif"
sprite_width = 20
sprite_height = 20
start_left = true
start_top = true

[spritesheets.sprite29]
name = "r-typesheet29"
path = "assets/img/r-typesheet29.gif"
sprite_width = 20
sprite_height = 20
start_left = true
start_top = true

[spritesheets.sprite30]
name = "r-typesheet30"
path = "assets/img/r-typesheet30.gif"
sprite_width = 20
sprite_height = 20
start_left = true
start_top = true

[spritesheets.sprite30a]
name = "r-typesheet30a"
path = "assets/img/r-typesheet30a.gif"
sprite_width = 20
sprite_height = 20
start_left = true
start_top = true

[spritesheets.sprite31]
name = "r-typesheet31"
path = "assets/img/r-typesheet31.gif"
sprite_width = 20
sprite_height = 20
start_left = true
start_top = true

[spritesheets.sprite32]
name = "r-typesheet32"
path = "assets/img/r-typesheet32.gif"
sprite_width = 20
sprite_height = 20
start_left = true
start_top = true

[spritesheets.sprite33]
name = "r-typesheet33"
path = "assets/img/r-typesheet33.gif"
sprite_width = 20
sprite_height = 20
start_left = true
start_top = true

[spritesheets.sprite34]
name = "r-typesheet34"
path = "assets/img/r-typesheet34.gif"
sprite_width = 20
sprite_height = 20
start_left = true
start_top = true

[spritesheets.sprite35]
name = "r-typesheet35"
path = "assets/img/r-typesheet35.gif"
sprite_width = 20
sprite_height = 20
start_left = true
start_top = true

[spritesheets.sprite36]
name = "r-typesheet36"
path = "assets/img/r-typesheet36.gif"
sprite_width = 20
sprite_height = 20
start_left = true
start_top = true

[spritesheets.sprite37]
name = "r-typesheet37"
path = "assets/img/r-typesheet37.gif"
sprite_width = 20
sprite_height = 20
start_left = true
start_top = true

[spritesheets.sprite38]
name = "r-typesheet38"
path = "assets/img/r-typesheet38.gif"
sprite_width = 20
sprite_height = 20
start_left = true
start_top = true

[spritesheets.sprite39]
name = "r-typesheet39"
path = "assets/img/r-typesheet39.gif"
sprite_width = 20
sprite_height = 20
start_left = true
start_top = true

[spritesheets.sprite40]
name = "r-typesheet40"
path = "assets/img/r-typesheet40.gif"
sprite_width = 20
sprite_height = 20
start_left = true
start_top = true

[spritesheets.sprite41]
name = "r-typesheet41"
path = "assets/img/r-typesheet41.gif"
sprite_width = 20
sprite_height = 20
start_left = true
start_top = true

[spritesheets.sprite42]
name = "r-typesheet42"
path = "assets/img/r-typesheet42.gif"
sprite_width = 20
sprite_height = 20
start_left = true
start_top = true

[spritesheets.sprite43]
name = "r-typesheet43"
path = "assets/img/r-typesheet43.gif"
sprite_width = 20
sprite_height = 20
start_left = true
start_top = true

[spritesheets.sprite44]
name = "r-typesheet44"
path = "assets/img/r-typesheet44.gif"
sprite_width = 20
sprite_height = 20
start_left = true
start_top = true
