@startuml The architecture of the repository

folder "R-Type" {
    folder ".github" {
        folder "workflows" {
            file "document_generator.yaml"
            file "epitech_mirrorer.yaml"
        }
    }
    folder "bonus" {
        folder "lessons" {
            file "B-CPP-500_rtype.pdf"
            file "B-CPP-500_rtype_apendix.pdf"
            file "B-CPP-500_rtype_bootstrap.pdf"
        }
        folder "notes" {
            file "debrief_du_27_11_2024.txt"
        }
        folder "plan" {
            file "folder_architecture.puml"
        }
        folder "ressources" {
            file "r-typesheet1.gif"
            file "r-typesheet2.gif"
            file "r-typesheet3.gif"
            file "r-typesheet5.gif"
            file "r-typesheet7.gif"
            file "r-typesheet8.gif"
            file "r-typesheet9.gif"
            file "r-typesheet10.gif"
            file "r-typesheet11.gif"
            file "r-typesheet12.gif"
            file "r-typesheet13.gif"
            file "r-typesheet14.gif"
            file "r-typesheet16.gif"
            file "r-typesheet17.gif"
            file "r-typesheet18.gif"
            file "r-typesheet19.gif"
            file "r-typesheet20.gif"
            file "r-typesheet21.gif"
            file "r-typesheet22.gif"
            file "r-typesheet23.gif"
            file "r-typesheet24.gif"
            file "r-typesheet25.gif"
            file "r-typesheet26.gif"
            file "r-typesheet27.gif"
            file "r-typesheet28.gif"
            file "r-typesheet29.gif"
            file "r-typesheet30.gif"
            file "r-typesheet30a.gif"
            file "r-typesheet31.gif"
            file "r-typesheet32.gif"
            file "r-typesheet33.gif"
            file "r-typesheet34.gif"
            file "r-typesheet35.gif"
            file "r-typesheet36.gif"
            file "r-typesheet37.gif"
            file "r-typesheet38.gif"
            file "r-typesheet39.gif"
            file "r-typesheet40.gif"
            file "r-typesheet41.gif"
            file "r-typesheet42.gif"
            file "r-typesheet43.gif"
            file "r-typesheet44.gif"
        }
    }
    folder "ecs" {
        file ".gitkeep"
    }
    folder "game_source" {
        file "\.gitkeep"
    }
    folder "network" {
        file "\\.gitkeep"
    }
    folder "assets" {
        file "\\\.gitkeep"
        ressources -> assets
    }
    folder "gui" {
        file "\\\\.gitkeep"
    }
    file "make.sh"
    file "README.md"
    file ".gitignore"
    file "CMakeList.txt"
    file "COMMIT_CONVENTION.md"
}

@enduml
